changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

compressionLevel: mixed

cacheFolder: .yarn/cache

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

httpTimeout: 300000

httpRetry: 10

networkConcurrency: 8

npmScopes:
  buf:
    npmRegistryServer: "https://buf.build/gen/npm/v1"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
